### PR TITLE
Added kotlin ktor server

### PR DESCRIPTION
**Pull request by fluxxion82**
Created a ktor server that is equivalent to the yarn server.

### CODE REVIEW

**Comment by fluxxion82** [comment]
Didn't want to install yarn so I made a kotlin ktor server. Figured others might want to use it as well. Should be the same functionally as the yarn server.

**Review by cgreening — CHANGES_REQUESTED** [review]
Looks great - instead of renaming the old server to "yarn", can we rename it to "javascript".

Thanks

**Comment by fluxxion82** [comment]
I  changed 'ktor' to kotlin too.

**Comment by cgreening** [comment]
Awesome!

**Pull request merged**
